name: crypto_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.0+1

environment:
  sdk: '>=2.17.3 <3.0.0'
  flutter: ">=3.0.2"

dependencies:
  bloc: ^8.1.0
  bloc_test: ^9.1.0
  build_runner: ^2.2.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_modular: ^5.0.3
  get_it: ^7.2.0
  http: ^0.13.5
  lottie: ^1.4.3
  mockito: ^5.3.2
  path_provider: ^2.0.11
  sembast: ^3.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
